$1.then(() => {
  $2
}).catch(err => {
  console.error(err)
})